
import java.net.*;
import java.io.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karan
 */
public class changepassword extends javax.swing.JFrame {

    /**
 
     */
    public changepassword(String u) {
        initComponents();
         this.setVisible(true);
        this.setSize(500, 500);
        tf1.setText(u);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        pf2 = new javax.swing.JPasswordField();
        pf3 = new javax.swing.JPasswordField();
        pf4 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setText("username");
        getContentPane().add(lb1);
        lb1.setBounds(60, 60, 60, 14);

        lb2.setText("old password");
        getContentPane().add(lb2);
        lb2.setBounds(60, 100, 63, 30);

        lb3.setText("new password");
        getContentPane().add(lb3);
        lb3.setBounds(60, 150, 69, 14);

        lb4.setText("confirm password");
        getContentPane().add(lb4);
        lb4.setBounds(60, 200, 84, 14);
        getContentPane().add(tf1);
        tf1.setBounds(190, 60, 160, 20);

        bt1.setText("Change password");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(110, 250, 130, 23);
        getContentPane().add(pf2);
        pf2.setBounds(190, 110, 150, 20);
        getContentPane().add(pf3);
        pf3.setBounds(190, 160, 150, 20);
        getContentPane().add(pf4);
        pf4.setBounds(190, 200, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       String op= pf2.getText() ;
       String np= pf3.getText() ;
         String cp= pf4.getText() ;
           String us= tf1.getText() ;
           if(np.equals(cp))
           {
               try
               {
                Socket sock = new Socket("localhost", 9000);

                        DataInputStream dis = new DataInputStream(sock.getInputStream());
                        DataOutputStream dos = new DataOutputStream(sock.getOutputStream());
                        dos.writeBytes("CHANGE PASSWORD REQUEST\r\n");
                        dos.writeBytes(us + "\r\n");
                        dos.writeBytes(op + "\r\n");
                        dos.writeBytes(np + "\r\n");
                        String r=dis.readLine();
                        if(r.equals("success"))
                        {
                            new start().setVisible(true);
                           dispose();
                        }
                        else
                        {
                                        JOptionPane.showMessageDialog(this, "Invalid old password");

                        }
               }
               catch(IOException ex)
               {
                   ex.printStackTrace();
               }
                                               


           }
           else
           {
                 JOptionPane.showMessageDialog(this, "confirm password and new password should be same ");

           }
    }//GEN-LAST:event_bt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepassword("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JPasswordField pf2;
    private javax.swing.JPasswordField pf3;
    private javax.swing.JPasswordField pf4;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
