import javax.swing.*;
import java.io.*;/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.net.Socket;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Karan
 */
public class signup extends javax.swing.JFrame {

    JFileChooser jfc;
    File f;

    public signup() {
        initComponents();
        this.setSize(500, 500);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        pf = new javax.swing.JPasswordField();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        lb6 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(pf);
        pf.setBounds(210, 90, 110, 20);

        lb1.setText("User name");
        getContentPane().add(lb1);
        lb1.setBounds(50, 50, 90, 20);

        lb2.setText("Password");
        getContentPane().add(lb2);
        lb2.setBounds(50, 80, 80, 30);

        lb3.setText("E-mail");
        getContentPane().add(lb3);
        lb3.setBounds(50, 120, 80, 30);

        lb4.setText("Phone number");
        getContentPane().add(lb4);
        lb4.setBounds(50, 160, 100, 30);

        lb5.setText("Photo");
        getContentPane().add(lb5);
        lb5.setBounds(50, 200, 60, 30);
        getContentPane().add(tf1);
        tf1.setBounds(210, 50, 110, 20);
        getContentPane().add(tf2);
        tf2.setBounds(210, 130, 110, 20);
        getContentPane().add(tf3);
        tf3.setBounds(210, 170, 110, 20);

        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 310, 120, 23);

        bt2.setText("Browse");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(230, 210, 67, 23);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Male", "Female" }));
        getContentPane().add(cb1);
        cb1.setBounds(220, 260, 80, 20);

        lb6.setText("Gender");
        getContentPane().add(lb6);
        lb6.setBounds(50, 260, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {

                String u = tf1.getText();
                String p = pf.getText();
                String e = tf2.getText();
                String ph = tf3.getText();
                String g =(String)(cb1.getSelectedItem());

                try {
                    Socket sock = new Socket("localhost", 9000);
                    DataInputStream dis = new DataInputStream(sock.getInputStream());
                    DataOutputStream dos = new DataOutputStream(sock.getOutputStream());
                    dos.writeBytes("SIGNUP REQUEST\r\n");
                    dos.writeBytes(u + "\r\n");
                    dos.writeBytes(p + "\r\n");
                    dos.writeBytes(e + "\r\n");
                    dos.writeBytes(ph + "\r\n");
                                        dos.writeBytes(g + "\r\n");


                    String r = dis.readLine();
                    if (r.equals("already exist")) {
                        JOptionPane.showMessageDialog(signup.this, "user already exist");
                    } else {

                        dos.writeLong(f.length());
                        FileInputStream fis = new FileInputStream(f);

                        long count = 0;
                        byte b[] = new byte[100000];
                        int q;
                        while (true) {
                            q = fis.read(b, 0, 100000);
                            count = count + q;
                            System.out.println(q);
                            if (q == -1) {
                                break;
                            }
                            dos.write(b, 0, q);
                            if (q == f.length()) {
                                break;
                            }
                        }
                        String s = dis.readLine();
                        System.out.println(s);
                       
                        JOptionPane.showMessageDialog(signup.this, "Signed Up successfully");
                         new start().setVisible(true);
                           dispose();
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }).start();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        jfc = new JFileChooser("C:\\");
         jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg"));
        jfc.setAcceptAllFileFilterUsed(false);

        int ans = jfc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            System.out.println(f);

        }
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt2;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JPasswordField pf;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
